### ISSUE TITLE
Classic ELB does not save aws_resource_id property

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-awssdk-plugin#140]

**Comment by gkatsaros** [comment]
@EarthmanT See [here](https://github.com/gkatsaros/aws-elb-blueprint/blob/master/elb.yaml)

**Comment by EarthmanT** [comment]
@gkatsaros 
If the VMs are existing resources, you should provide the `cloudify.nodes.aws.ec2.Instances ` node property `resource_id` along with the `use_external_resource`.
See the [docs on common properties for the plugin](https://docs.cloudify.co/4.3.0/working_with/official_plugins/awssdk/#common-properties).

Why are you using `aws_resource_id` operation input instead of `resource_id`?

**Comment by gkatsaros** [comment]
@EarthmanT I had found an example BP with the use_external_resource and input of aws_resource_id. It did not give any error and the resource seems to be picked up correctly for the VMs. I will give it a try though.

**Comment by EarthmanT** [comment]
Hi @gkatsaros. First, thanks for contacting about the issue.
After testing your blueprint, I've identified two possible reasons that this behavior is occuring.
We are now working on addressing both of the changes.

1. Because the VM nodes are "external nodes" no relationship operation is occuring to add the VM to the LB backend. This is based on an old convention in Cloudify that nothing happens on external nodes. However, after considering it, the convention is flawed. I believe that the following logic is more desire-able:

- Resource A is external, Resource B is external + Resource A connected to Resource B -> No connection operation is performed in relationship.
- Resource A is external, Resource B is new + Resource A is connected to Resource B -> Perform relationship from Resource A to Resource B.
- Resource A is new, Resource B is external + Resource A is connected to Resource B -> Perform relationship from Resource A to Resource B.

2. It seems like there is a race condition when 1 or more VMs are being added to a ELB simultaneously. We will need to do some state verification in the code.

Please expect to see a new version of the plugin shortly with the updated changes.

**Comment by gkatsaros** [comment]
@EarthmanT Thank you very much for your help. I believe that with the suggested changes my blueprint and execution scenario will work. 
Can I ask the reasoning for the first bullet? What is I want to orchestrate just the relationship between existing resources? Is it a valid use case? (I guess that is highly dependant on the implementation of each plugin, but could be a case if an API call is captured only through a relationship implementation.).

Thx again! 

Looking forward to the new release.

**Comment by EarthmanT** [comment]
@gkatsaros 
There are two reasons why.

Consider the following case.

```yaml
node_templates:

  node1:

  node2:
    properties:
      resource_id: node2
      use_external_resource: true

  node3:
    properties:
      resource_id: node3
      use_external_resource: true
    relationships:
    - target: node1
       type: cloudify.relationships.connected_to
    - target: node2
       type: cloudify.relationships.connected_to
```

In this case, more than one existing resources are connected, and no action will be expected, but an additional new node is also in the relationship list.

**Comment by EarthmanT** [comment]
@gkatsaros 
Issue should be fixed in this release:
https://github.com/cloudify-incubator/cloudify-awssdk-plugin/releases/tag/2.5.0
#160

**Comment by gkatsaros** [comment]
@EarthmanT I used this release, one instance was indeed registered in the ELB, however the second and third instance are not registered. Is that a normal behaviour or there is still an issue?

Thx

**Comment by gkatsaros** [comment]
LOL. Good catch. Thx!
